language: node_js
node_js: "7"
install:
- npm install
script:
- npm test
env:
- NODE_ENV=test
cache:
  directories:
   - "node_modules"
services:
  - postgresql
before_script:
- npm install nyc -g
- npm install mocha -g
- createdb More-Recipes-test --username=postgres
- sequelize db:migrate
- sequelize db:seed:all
notifications:
  webhooks: https://coveralls.io/webhook 
  repo_token: AkyDA6kofzdIYNKaC3ncj7wTDsYwTpMEq