

const ADD_ARTICLE = 'ADD_ARTICLE';

// App Notification Actions
export const DISPLAY_APP_NOTIFICATION = 'DISPLAY_APP_NOTIFICATION';
export const TOGGLE_APP_NOTIFICATION = 'TOGGLE_APP_NOTIFICATION';

export const ADD_USER = 'ADD_USER';
export const USER_IS_REGISTERING = 'USER_IS_REGISTERING';
export const USER_REGISTRATION_ERRORED = 'USER_REGISTRATION_ERRORED';
export const USER_IS_ATTEMPTING_LOGIN = 'USER_IS_ATTEMPTION_LOGIN';
export const USER_LOGIN_ERRORED = 'USER_LOGIN_ERRORED';
export const USER_LOGIN_SUCCESSFUL = 'USER_LOGIN_SUCCESSFUL';
export const USER_LOGGED_OUT_SUCCESSFUL = 'USER_LOGGED_OUT_SUCCESSFUL';
export const GET_USER_RECIPE_POSTERS = 'GET_USER_RECIPE_POSTERS';

// Recipe Actions
export const ADD_RECIPE = 'ADD_RECIPE';
export const SET_POSTER_ON_ADD_RECIPE = 'SET_POSTER_ON_ADD_RECIPE';
export const RESET_NO_MORE_RECIPE_ON_ADD_RECIPE = 'RESET_NO_MORE_RECIPE_ON_ADD_RECIPE';
export const RETRIEVING_MY_RECIPES = 'RETRIEVING_MY_RECIPES';

export default ADD_ARTICLE;
